// app/app/components/Footer.tsx
'use client';

import Link from 'next/link';
import { URLs, PALM_BASE_URL } from '@/app/constants/urls';

const footerSections = [
  {
    title: '项目开源',
    links: [
      {
        name: 'GitHub 仓库',
        url: URLs.github.repository,
      },
      {
        name: '关于开发者',
        url: URLs.github.personal,
      },
    ],
  },
  {
    title: '联系我们',
    links: [
      {
        name: '联系导师',
        url: `${PALM_BASE_URL}members.html`,
      },
      {
        name: '联系招生老师',
        url: URLs.contact,
      },
      {
        name: '联系开发者',
        url: URLs.github.personal,
      },
    ],
  },
  {
    title: '更多网站',
    links: [
      {
        name: '东南大学官网',
        url: URLs.seu.main,
      },
      {
        name: '东南大学计算机学院',
        url: URLs.seu.cs,
      },
      {
        name: '东大计软智常用网址',
        url: URLs.seu.commonLinks,
      },
    ],
  },
  {
    title: '关于 PALM',
    links: [
      {
        name: 'PALM 实验室',
        url: PALM_BASE_URL,
      },
      {
        name: '研究生申请指南',
        url: `${PALM_BASE_URL}application.html`,
      },
      {
        name: '实验室成员',
        url: `${PALM_BASE_URL}members.html`,
      },
    ],
  },
];

export default function Footer() {
  const handleExternalLink = (url: string) => {
    if (url.startsWith('http')) {
      window.open(url, '_blank', 'noopener,noreferrer');
    }
  };

  return (
    <footer
      className="w-full mt-0 py-5 sm:py-10 px-4 sm:px-6 lg:px-8"
      style={{
        backgroundImage: "url('/home-bg-m.png')",
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
      }}
    >
      <div className="mx-auto max-w-screen-lg px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col sm:flex-row gap-4 sm:gap-8">
          {footerSections.map((section, index) => (
            <div key={index} className="mx-auto my-0 md:text-left">
              <h3 className="text-gray-700 font-bold mb-2">{section.title}</h3>
              <ul className="space-y-2">
                {section.links.map((link, linkIndex) => (
                  <li key={linkIndex}>
                    {link.url.startsWith('http') ? (
                      <a
                        href={link.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-gray-700 hover:text-blue-500"
                      >
                        {link.name}
                      </a>
                    ) : (
                      <Link href={link.url} className="text-gray-700 hover:text-blue-500">
                        {link.name}
                      </Link>
                    )}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <div className="mt-8 sm:mt-10 border-t border-gray-700/30 pt-5 sm:pt-10">
          <p className="text-center text-gray-700">
            CopyRight ©{' '}
            <a
              href={URLs.github.personal}
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-500"
            >
              何锦诚
            </a>{' '}
            | 刘宇轩 | 戴雨成 | 胡瀚 <br className="md:hidden" /> 2025 All rights reserved.
          </p>
          <p className="text-center text-gray-700 mt-3">东南大学 2025 年创业实践项目作品</p>
        </div>
      </div>

      <style jsx>{`
        footer {
          box-shadow: 0 -2px 4px rgba(0, 0, 0, 0.1);
        }
      `}</style>
    </footer>
  );
}

// front-vite/src/views/layout/components/Footer.vue
<template>
  <footer class="w-full mt-0 py-5 sm:py-10 px-4 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-screen-lg px-4 sm:px-6 lg:px-8">
      <!-- 使用 flex 布局替换 grid 布局 -->
      <div class="flex flex-col sm:flex-row gap-4 sm:gap-8">
        <div v-for="(section, index) in footerSections" :key="index" class="mx-auto my-0 md:text-left">
          <h3 class="text-gray-500 font-bold mb-2">{{ section.title }}</h3>
          <ul class="space-y-2">
            <li v-for="(link, linkIndex) in section.links" :key="linkIndex">
              <a :href="link.url" target="_blank" class="text-gray-500 hover:text-blue-500">
                {{ link.name }}
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class="mt-8 sm:mt-10 border-t border-white pt-5 sm:pt-10">
        <p class="text-center text-gray-500">
          CopyRight © <a href="https://inon.space" target="_blank" rel="noopener noreferrer" class="text-blue-500">何锦诚</a> | 刘宇轩 | 戴雨成 | 胡瀚 <br class="md:hidden">2025 All rights reserved.
        </p>
        <p class="text-center text-gray-500 mt-3">
          东南大学 2025 年创业实践项目作品
        </p>
      </div>
    </div>
  </footer>
</template>

<style scoped>
footer {
  box-shadow: 0 -2px 4px rgba(0, 0, 0, 0.1);
}
</style>

<script>
export default {
  data() {
    return {
      footerSections: [
        {
          title: '项目开源',
          links: [
            {
              name: '个人项目',
              url: 'https://github.com/JacksonHe04',
              // icon: 'i iconfont icon-github'
            },
            {
              name: 'GitHub 仓库',
              url: 'https://github.com/JacksonHe04/PalmAdmissionsSystem',
              // icon: 'i iconfont icon-github'
            }
          ]
        },
        {
          title: '联系我们',
          links: [
            {
              name: '联系管理员',
              url: '/contact'
            },
            {
              name: '联系开发者',
              url: '/contact'
            }
          ]
        },
        {
          title: '更多网站',
          links: [
            {
              name: '东南大学官网',
              url: 'https://www.seu.edu.cn/'
            },
            {
              name: '东南大学计算机学院',
              url: 'https://cs.seu.edu.cn/'
            },
            {
              name: '东大计软智常用网址',
              url: 'https://seucseweb.github.io/'
            }
          ]
        },
        {
          title: '关于 PALM',
          links: [
            {
              name: 'PALM 实验室',
              url: 'https://palm.seu.edu.cn/'
            },
            {
              name: '研究生申请指南',
              url: 'https://palm.seu.edu.cn/application.html'
            },
            {
              name: '实验室成员',
              url: 'https://palm.seu.edu.cn/members.html'
            }
          ]
        }
      ]
    };
  }
};
</script>
