// front-vite/src/views/front-desk/home/components/HomeCards.vue
<template>
  <div class="cards mt-0">
    <a :href="`${PALM_BASE_URL}application.html`" target="_blank">
      <div class="stats-card h-full">
        <div class="stats-number">Join Us</div>
        <div>请阅读PALM实验室招生说明</div>
        <div class="mt-2 read">点击阅读</div>
      </div>
    </a>

    <div class="small-cards-list">
      <a :href="PALM_BASE_URL" target="_blank">
        <div class="horizontal-card">
          <div class="flex justify-center">
            <!-- <div
              class="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center"
            >
              🤖
            </div> -->
            <div>
              <div style="font-weight: 600">
                东南大学 PALM 实验室
              </div>
              <p style="font-size: 14px; color: #6b7280; margin-top: 4px">
                计算机科学与工程学院
              </p>
              <div style="margin-top: 8px">了解详情</div>
            </div>
          </div>
        </div>
      </a>

      <div class="small-cards">
        <a v-for="(card, index) in smallCards" :key="index" :href="card.href " target="_blank">
          <div class="small-card">
            <span>{{ card.icon }}</span>
            <div>{{ card.title }}</div>
          </div>
        </a>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";
import { PALM_BASE_URL } from '@/config/baseUrl';

// 当前招生年份 - 使用默认值，避免首页加载时发起网络请求
const currentAdmissionYear = ref("2025");

const smallCards = ref([
  {
    icon: "👥",
    title: "PALM 实验室简介",
    href: `${PALM_BASE_URL}home.html`,
  },
  {
    icon: "👩‍🎓",
    title: "研究队伍及人才培养",
    href: `${PALM_BASE_URL}members.html`,
  },
  {
    icon: "🎓",
    title: "科学研究及主要成果",
    href: `${PALM_BASE_URL}publication.html`,
  },
  {
    icon: "📚️",
    title: "科研资源共享",
    href: `${PALM_BASE_URL}projects.html`,
  },
]);
</script>

<style scoped lang="scss">
$primary-color: #3b82f6;
$secondary-color: #1f2937;
$text-color: #6b7280;
$white-color: white;
$hover-bg-color: wheat;

/* Features Grid */
.cards {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 32px;
}

.stats-card {
  background: $secondary-color;
  color: $white-color;
  padding: 32px;
  border-radius: 16px;
  .read {
    color: $hover-bg-color;
  }
}

.stats-card:hover {
  color: $hover-bg-color;
}

.stats-number {
  font-size: 36px;
  font-weight: bold;
  margin-bottom: 16px;
}

.bubble-cards {
  background: $primary-color;
  padding: 32px;
  border-radius: 16px;
  color: $white-color;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
}

.bubble-item {
  background: rgba(255, 255, 255, 0.2);
  padding: 8px 16px;
  border-radius: 20px;
  // margin-bottom: 12px;
  display: inline-block;
  width: fit-content;
}

.small-cards-list {
  display: flex;
  flex-direction: column;
  gap: 24px;
}

.horizontal-card {
  background: $white-color;
  padding: 16px;
  border-radius: 12px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.horizontal-card:hover {
  background: $hover-bg-color;
}

.small-cards {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 24px;
  a {
    .small-card {
      span {
        font-size: 24px;
      }
      div {
        font-size: 14px;
        margin-top: 8px;
      }
    }
  }
}

.small-card:hover {
  background: $hover-bg-color;
}

.small-card {
  background: $white-color;
  padding: 16px;
  border-radius: 12px;
  text-align: center;

  a:hover {
    background: transparent;
  }
}

.btn {
  padding: 12px 24px;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.btn-apply {
  background-color: $primary-color;
  color: $white-color;
}

.btn-apply:hover {
  background-color: $hover-bg-color;
}

/* Responsive Design */
@media (max-width: 768px) {
  .cards {
    grid-template-columns: 1fr;
  }
}
</style>

// app/app/components/HomeCards.tsx
import { Users, GraduationCap, BookOpen, Library, ArrowRight } from 'lucide-react';

const PALM_BASE_URL = 'http://8.149.133.61/';

const smallCards = [
  {
    icon: Users,
    title: 'PALM 实验室简介',
    href: `${PALM_BASE_URL}intro.html`,
  },
  {
    icon: GraduationCap,
    title: '研究队伍及人才培养',
    href: `${PALM_BASE_URL}members.html`,
  },
  {
    icon: BookOpen,
    title: '科学研究及主要成果',
    href: `${PALM_BASE_URL}publication.html`,
  },
  {
    icon: Library,
    title: '科研资源共享',
    href: `${PALM_BASE_URL}projects.html`,
  },
];

export default function HomeCards() {
  return (
    <div className="cards-grid">
      <a href={`${PALM_BASE_URL}application.html`} target="_blank" rel="noopener noreferrer">
        <div className="stats-card h-full">
          <div className="stats-number">Join Us</div>
          <div>请阅读PALM实验室招生说明</div>
          <div className="join-cta">
            <span>点击阅读</span>
            <ArrowRight size={16} />
          </div>
        </div>
      </a>

      <div className="small-cards-list">
        <a href={`${PALM_BASE_URL}`} target="_blank" rel="noopener noreferrer">
          <div className="horizontal-card">
            <div className="flex items-center justify-center gap-8">
              <img src="/palm_logo_cicle.png" alt="PALM Logo" style={{ width: '48px', height: '48px' }} />
              <div>
                <div className="lab-title">东南大学 PALM 实验室</div>
                <p className="lab-subtitle">计算机科学与工程学院</p>
              </div>
            </div>
          </div>
        </a>

        <div className="small-cards">
          {smallCards.map((card, index) => {
            const IconComponent = card.icon;
            return (
              <a key={index} href={card.href} target="_blank" rel="noopener noreferrer">
                <div className="small-card">
                  <div className="card-icon-wrapper">
                    <IconComponent size={24} strokeWidth={1.5} />
                  </div>
                  <div className="card-title">{card.title}</div>
                </div>
              </a>
            );
          })}
        </div>
      </div>
    </div>
  );
}
